name: climate-cockpit
dependencies:
  - python=3.11.3
  - pip=23.2.1
  - psycopg2=2.9.3
  - pip:
      - Django==4.2.7
      - djangorestframework==3.14.0
      - djangorestframework-simplejwt==5.3.0
      - django-cors-headers==4.3.0
      - django-extensions==3.2.3
      - django-fullurl==1.4
      - drf-yasg==1.21.7
      - gunicorn==21.2.0
      - Pillow==10.1.0
      - ruff==0.1.3
      - openai==1.2.4
