# Generated by Django 4.2.7 on 2023-11-08 10:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="memberships",
            field=models.JSONField(blank=True, default=list, max_length=30),
        ),
    ]
