# Generated by Django 4.2.7 on 2023-11-15 23:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_alter_user_memberships"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="gptbot_description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="user",
            name="is_gptbot",
            field=models.BooleanField(default=False),
        ),
    ]
