# Generated by Django 4.2.7 on 2023-11-07 15:13

import django.db.models.deletion
import django_extensions.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
            options={
                "get_latest_by": "modified",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Solution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("shorter_name", models.CharField(max_length=255)),
                ("impact", models.FloatField(blank=True, null=True)),
                (
                    "text",
                    models.TextField(
                        help_text=(
                            "To include impact in text, use: "
                            "text.replace('{impact}', impact + '%')"
                        )
                    ),
                ),
                ("text_source", models.URLField(blank=True, max_length=500)),
                ("progress", models.FloatField(blank=True, null=True)),
                (
                    "progress_text",
                    models.TextField(
                        help_text=(
                            "To include progress in progress_text, "
                            "use: progress_text.replace('{progress}', progress + '%')"
                        )
                    ),
                ),
                ("progress_source", models.URLField(blank=True, max_length=500)),
                ("button_text", models.CharField(max_length=255)),
                ("icon_name", models.CharField(max_length=255)),
                ("level", models.IntegerField()),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="solutions",
                        to="solution.category",
                    ),
                ),
            ],
            options={
                "unique_together": {("category", "level")},
            },
        ),
        migrations.CreateModel(
            name="UserSelection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "selected_solutions",
                    models.ManyToManyField(
                        blank=True,
                        related_name="user_selections",
                        to="solution.solution",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_selections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "get_latest_by": "modified",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("source", models.CharField(blank=True, max_length=100)),
                ("author", models.CharField(blank=True, max_length=100)),
                ("url", models.URLField(blank=True, max_length=500)),
                (
                    "resource_type",
                    models.CharField(
                        choices=[("videos", "videos"), ("news", "news")],
                        default="videos",
                        help_text="Select from ['videos', 'news']",
                        max_length=20,
                    ),
                ),
                (
                    "solution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resources",
                        to="solution.solution",
                    ),
                ),
            ],
            options={
                "get_latest_by": "modified",
                "abstract": False,
            },
        ),
    ]
