# Generated by Django 4.2.7 on 2023-11-12 14:27

import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("solution", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DashboardGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("subgroup_name", models.CharField(max_length=100)),
            ],
            options={
                "unique_together": {("name", "subgroup_name")},
            },
        ),
        migrations.CreateModel(
            name="DashboardItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("initial_amount", models.IntegerField()),
                (
                    "altered_type",
                    models.CharField(
                        blank=True,
                        choices=[("reduction", "reduction"), ("addition", "addition")],
                        help_text="Select from ['reduction', 'addition']",
                        max_length=20,
                    ),
                ),
                ("icon_name_initial", models.CharField(blank=True, max_length=255)),
                ("icon_name_altered", models.CharField(blank=True, max_length=255)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dashboard_icons",
                        to="solution.dashboardgroup",
                    ),
                ),
            ],
            options={
                "get_latest_by": "modified",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ImpactDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.IntegerField()),
                (
                    "dashboard_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="impact_detail",
                        to="solution.dashboarditem",
                    ),
                ),
            ],
            options={
                "unique_together": {("dashboard_item", "amount")},
            },
        ),
        migrations.CreateModel(
            name="SelectionRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="SolutionLogic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "impact_detail",
                    models.ManyToManyField(
                        blank=True,
                        related_name="solution_logic",
                        to="solution.impactdetail",
                    ),
                ),
                (
                    "selection_rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="solution_logics",
                        to="solution.selectionrule",
                    ),
                ),
                (
                    "solution",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="solution_logic",
                        to="solution.solution",
                    ),
                ),
            ],
        ),
    ]
